  [[main]]
  name = "随笔"
  identifier = "post"
  weight = 100
  url = "/"

  [[main]]
  name = "合辑"
  weight = 200
  identifier = "series"
  url = "/series/"

  [[footer]]
  name = "Powered by Hugo with Anatole Theme"
  weight = 1
  identifier = "theme"
  url = "https://themes.gohugo.io/themes/anatole/"
